[SERVICE]
    Flush        1
    Grace        30
    Log_Level    info
    Parsers_File parsers.conf

[FILTER]
    Name         modify
    Match        *
    Add          service_name ${SERVICE_NAME}
    Add          environment ${ENVIRONMENT_NAME}
    Add          region ${AWS_REGION}
    Add          openapm_product_name ${OPENAPM_PRODUCT_NAME}
    Add          account_id ${ACCOUNT_ID}

[OUTPUT]
    Name         http
    Match        *
    Host         ${OTEL_ENDPOINT_HOST}
    Port         ${OTEL_ENDPOINT_PORT}
    URI          /loki/api/v1/push
    Format       json
    tls          On
    tls.verify   On
    Retry_Limit  3
    Header       Content-Type application/json
