[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On

[PARSER]
    Name         python_log
    Format       regex
    Regex        ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?<level>\S+) (?<logger>\S+) (?<message>.*)$
    Time_Key     time
    Time_Format  %Y-%m-%d %H:%M:%S,%L
    Time_Keep    On
